# Generated by Django 6.0.5 on 2026-08-16 09:02

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('reason', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_minutes', models.PositiveIntegerField(default=30)),
                ('video_enabled', models.BooleanField(default=True)),
                ('auto_accept', models.BooleanField(default=False)),
                ('clinic_fee', models.PositiveIntegerField(default=800)),
                ('video_fee', models.PositiveIntegerField(default=500)),
            ],
        ),
        migrations.CreateModel(
            name='Hours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(unique=True)),
                ('opens', models.TimeField(default=datetime.time(9, 0))),
                ('closes', models.TimeField(default=datetime.time(17, 0))),
                ('break_start', models.TimeField(blank=True, default=datetime.time(13, 0), null=True)),
                ('break_end', models.TimeField(blank=True, default=datetime.time(14, 0), null=True)),
            ],
            options={
                'ordering': ['weekday'],
            },
        ),
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=15)),
                ('code', models.CharField(max_length=6)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('mode', models.CharField(default='clinic', max_length=6)),
                ('reason', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(default='held', max_length=10)),
                ('payment', models.CharField(default='clinic', max_length=10)),
                ('lang', models.CharField(default='en', max_length=2)),
                ('hold_expires', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'time'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ('held', 'pending', 'confirmed'))), fields=('date', 'time'), name='one_live_appointment_per_slot')],
            },
        ),
    ]
