# Generated by Django 6.0.5 on 2026-08-20 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_appointment_fee_amount_appointment_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='assessed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='problem',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='progress',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='suggestions',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('kind', models.CharField(default='note', max_length=6)),
                ('text', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/')),
                ('by_doctor', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='api.patient')),
            ],
            options={
                'ordering': ['-date', '-created'],
            },
        ),
    ]
