// Every string the user sees, English first, Nepali second.
//
// A flat object beats an i18n library here: there are two languages, no
// pluralisation rules that differ between them, and the whole table fits in
// one file. `{name}` placeholders are filled by t()'s second argument.
//
// Drug names, phone numbers and money stay in Latin script in both languages —
// that is how they are written on a Nepali prescription pad.

export const strings = {
  // --- chrome ---------------------------------------------------------------
  appName: ['Sanjivani Clinic', 'सञ्जीवनी क्लिनिक'],
  doctorName: ['Dr. Anjana Shrestha', 'डा. अञ्जना श्रेष्ठ'],
  doctorTitle: ['MBBS, MD — General Physician', 'एमबीबीएस, एमडी — जनरल फिजिसियन'],
  navHome: ['Home', 'गृहपृष्ठ'],
  navBook: ['Book', 'बुक गर्नुहोस्'],
  navAccount: ['My account', 'मेरो खाता'],
  navDashboard: ['Today', 'आज'],
  navPatients: ['Patients', 'बिरामीहरू'],
  navAnalytics: ['Analytics', 'तथ्याङ्क'],
  signIn: ['Sign in', 'साइन इन'],
  signOut: ['Sign out', 'साइन आउट'],
  language: ['Language', 'भाषा'],
  loading: ['Loading…', 'लोड हुँदै…'],
  retry: ['Try again', 'फेरि प्रयास गर्नुहोस्'],
  save: ['Save', 'सुरक्षित गर्नुहोस्'],
  saving: ['Saving…', 'सुरक्षित हुँदै…'],
  saved: ['Saved', 'सुरक्षित भयो'],
  cancel: ['Cancel', 'रद्द गर्नुहोस्'],
  close: ['Close', 'बन्द गर्नुहोस्'],
  back: ['Back', 'पछाडि'],
  next: ['Continue', 'अगाडि बढ्नुहोस्'],
  optional: ['optional', 'ऐच्छिक'],
  none: ['None', 'केही छैन'],
  notFound: ['Nothing here.', 'यहाँ केही छैन।'],

  // --- landing --------------------------------------------------------------
  heroKicker: ['General practice · Kathmandu', 'जनरल प्राक्टिस · काठमाडौं'],
  heroTitle: ['Trusted care for every stage of life', 'जीवनको हरेक चरणमा भरपर्दो उपचार'],
  heroBody: [
    'Book a time with Dr. Anjana Shrestha at the clinic, and keep every prescription, report and follow-up in one place.',
    'डा. अञ्जना श्रेष्ठसँग क्लिनिकमा समय बुक गर्नुहोस्, र आफ्ना सबै औषधि, रिपोर्ट र फलोअप एकै ठाउँमा राख्नुहोस्।',
  ],
  heroCta: ['Book an appointment', 'अपोइन्टमेन्ट बुक गर्नुहोस्'],
  heroSecondary: ['See my record', 'मेरो रेकर्ड हेर्नुहोस्'],
  aboutDoctor: ['About the doctor', 'डाक्टरको बारेमा'],
  doctorBio: [
    'Dr. Anjana Shrestha has practised general medicine in Kathmandu for eighteen years. She sees adults and children, and treats the long conditions — blood pressure, diabetes, thyroid — that need someone who remembers you between visits.',
    'डा. अञ्जना श्रेष्ठले काठमाडौंमा अठार वर्षदेखि जनरल मेडिसिनको अभ्यास गर्दै आउनुभएको छ। उहाँले वयस्क र बालबालिका दुवैलाई हेर्नुहुन्छ, र रक्तचाप, मधुमेह, थाइराइड जस्ता दीर्घ रोगहरूको उपचार गर्नुहुन्छ — जसका लागि तपाईंलाई सम्झिने डाक्टर चाहिन्छ।',
  ],
  clinicInfo: ['The clinic', 'क्लिनिक'],
  clinicAddress: ['Dhobighat, Lalitpur', 'धोबीघाट, ललितपुर'],
  clinicAddressLine: ['Ring Road, opposite the water tank', 'रिङरोड, पानी ट्याङ्कीको ठीक पारि'],
  clinicPhone: ['01-5555120', '०१-५५५५१२०'],
  openingHours: ['Opening hours', 'खुल्ने समय'],
  closed: ['Closed', 'बन्द'],
  consultationFee: ['Consultation fee', 'परामर्श शुल्क'],
  feeNote: ['Paid at the clinic desk on the day.', 'सोही दिन क्लिनिकको काउन्टरमा तिर्नुहोस्।'],
  inPersonOnly: ['In-person visits only', 'भेटघाट मात्र'],
  inPersonNote: [
    'Every appointment is at the clinic. There is no video consultation.',
    'सबै अपोइन्टमेन्ट क्लिनिकमै हुन्छ। भिडियो परामर्श उपलब्ध छैन।',
  ],
  nextAvailable: ['Next available', 'अर्को उपलब्ध समय'],
  slotsFree: ['{n} free', '{n} खाली'],
  howItWorks: ['How it works', 'यसरी काम गर्छ'],
  step1Title: ['Pick a time', 'समय छान्नुहोस्'],
  step1Body: ['Fourteen days of the doctor\'s diary, live.', 'डाक्टरको चौध दिनको तालिका, तत्कालै।'],
  step2Title: ['Confirm with your phone', 'फोनबाट पुष्टि गर्नुहोस्'],
  step2Body: ['A code by SMS. No password to remember.', 'एसएमएसमा कोड आउँछ। पासवर्ड सम्झनु पर्दैन।'],
  step3Title: ['Bring the slip', 'पर्ची लिएर आउनुहोस्'],
  step3Body: ['Print it or show the QR code at the desk.', 'प्रिन्ट गर्नुहोस् वा काउन्टरमा QR देखाउनुहोस्।'],
  step4Title: ['Keep your record', 'आफ्नो रेकर्ड राख्नुहोस्'],
  step4Body: ['Prescriptions and reports stay in your account.', 'औषधि र रिपोर्टहरू तपाईंको खातामा रहन्छन्।'],

  yearsPractising: ['18+', '१८+'],
  yearsPractisingLabel: ['Years in practice', 'अभ्यासका वर्ष'],
  openDaysLabel: ['Days of diary open now', 'अहिले खुला तालिकाका दिन'],
  aboutHeadline: [
    'More than a clinic — your health partner',
    'क्लिनिकभन्दा बढी — तपाईंको स्वास्थ्य साथी',
  ],
  clinicHeadline: ['Quality healthcare, closer to home', 'गुणस्तरीय स्वास्थ्य सेवा, तपाईंकै नजिक'],
  servicesHeadline: ['What the clinic looks after', 'क्लिनिकले हेर्ने कुराहरू'],
  ctaHeadline: [
    'Walk in or book online — we are ready',
    'सिधै आउनुहोस् वा अनलाइन बुक गर्नुहोस् — हामी तयार छौं',
  ],
  quotesHeadline: [
    'Compassion you can feel, care you can trust',
    'महसुस हुने माया, भरोसा लाग्ने उपचार',
  ],
  photoPending: ['Photo', 'फोटो'],

  svc1Title: ['General consultation', 'सामान्य परामर्श'],
  svc1Body: [
    'Fever, infections, aches and the everyday complaints — seen the same week, often the same day.',
    'ज्वरो, संक्रमण, दुखाइ र दैनिक समस्याहरू — सोही हप्ता, प्रायः सोही दिन जाँच।',
  ],
  svc2Title: ['Long-term conditions', 'दीर्घ रोगहरू'],
  svc2Body: [
    'Blood pressure, diabetes and thyroid, followed by a doctor who remembers you between visits.',
    'रक्तचाप, मधुमेह र थाइराइड — भेटहरूबीच तपाईंलाई सम्झिने डाक्टरको निगरानीमा।',
  ],
  svc3Title: ['Children and vaccination', 'बालबालिका र खोप'],
  svc3Body: [
    'Child check-ups and the routine immunisation schedule, kept on your record.',
    'बालबालिकाको जाँच र नियमित खोपको तालिका, तपाईंकै रेकर्डमा सुरक्षित।',
  ],
  svc4Title: ['Lab reports and follow-up', 'ल्याब रिपोर्ट र फलोअप'],
  svc4Body: [
    'Bring or upload a report; the doctor reads it and writes back into your account.',
    'रिपोर्ट ल्याउनुहोस् वा अपलोड गर्नुहोस्; डाक्टरले पढेर तपाईंको खातामा जवाफ लेख्नुहुन्छ।',
  ],

  // Sample quotes for the testimonial band — replace with real, consented
  // patient words before launch. Names are deliberately left as placeholders.
  quoteName: ['Patient name', 'बिरामीको नाम'],
  quotePlace: ['Lalitpur', 'ललितपुर'],
  quote1: [
    'Booked in the morning, seen in the afternoon. The slip on my phone was all the desk needed.',
    'बिहान बुक गरें, दिउँसो जाँच भयो। काउन्टरमा फोनको पर्ची नै पुग्यो।',
  ],
  quote2: [
    'She remembers my mother\'s blood pressure history without opening a file. That is why we keep coming back.',
    'फाइल नखोली उहाँले मेरी आमाको रक्तचापको इतिहास सम्झनुहुन्छ। त्यसैले हामी फेरि आउँछौं।',
  ],
  quote3: [
    'Every prescription and lab report sits in one place. No more plastic bag full of papers.',
    'सबै औषधि र ल्याब रिपोर्ट एकै ठाउँमा। अब कागजले भरिएको झोला बोक्नु परेन।',
  ],

  footerMenu: ['Menu', 'मेनु'],
  footerContact: ['Contact', 'सम्पर्क'],
  footerRights: ['All rights reserved.', 'सर्वाधिकार सुरक्षित।'],

  // --- booking --------------------------------------------------------------
  bookTitle: ['Book an appointment', 'अपोइन्टमेन्ट बुक गर्नुहोस्'],
  stepDay: ['Choose a day', 'दिन छान्नुहोस्'],
  stepTime: ['Choose a time', 'समय छान्नुहोस्'],
  stepDetails: ['Who is the visit for?', 'यो भेट कसका लागि हो?'],
  stepConfirm: ['Confirm', 'पुष्टि गर्नुहोस्'],
  dayClosed: ['Closed', 'बन्द'],
  dayFull: ['Full', 'भरियो'],
  pickDayFirst: ['Choose a day above to see times.', 'समय हेर्न माथि दिन छान्नुहोस्।'],
  noSlots: ['No times left on this day. Try another.', 'यस दिन कुनै समय बाँकी छैन। अर्को दिन हेर्नुहोस्।'],
  taken: ['Taken', 'लिइसकिएको'],
  holdingSlot: ['This time is held for you — {mm}:{ss} left', 'यो समय तपाईंका लागि रोकिएको छ — {mm}:{ss} बाँकी'],
  holdExpired: ['Your hold ran out. Choose a time again.', 'तपाईंको समय सकियो। फेरि समय छान्नुहोस्।'],
  patientName: ['Patient\'s full name', 'बिरामीको पूरा नाम'],
  patientNameHint: [
    'Booking for someone else? Use their name — the clinic keeps a record per person.',
    'अरू कसैका लागि बुक गर्दै हुनुहुन्छ? उनकै नाम लेख्नुहोस् — क्लिनिकले हरेक व्यक्तिको छुट्टै रेकर्ड राख्छ।',
  ],
  patientAge: ['Age', 'उमेर'],
  visitReason: ['What is the visit about?', 'भेटको कारण के हो?'],
  visitReasonHint: ['A few words: "fever", "blood pressure check".', 'केही शब्दमा: "ज्वरो", "रक्तचाप जाँच"।'],
  visitNotes: ['Anything the doctor should know beforehand', 'डाक्टरले पहिल्यै जान्नुपर्ने कुरा'],
  reviewHeading: ['Check this over', 'एकपटक जाँच्नुहोस्'],
  reviewWhen: ['When', 'कहिले'],
  reviewWho: ['Who', 'को'],
  reviewWhere: ['Where', 'कहाँ'],
  reviewReason: ['Reason', 'कारण'],
  reviewFee: ['Fee', 'शुल्क'],
  confirmBooking: ['Confirm booking', 'बुकिङ पुष्टि गर्नुहोस्'],
  booking: ['Booking…', 'बुक हुँदै…'],
  years: ['{n} years', '{n} वर्ष'],

  // --- otp ------------------------------------------------------------------
  signInTitle: ['Sign in with your phone', 'आफ्नो फोनबाट साइन इन गर्नुहोस्'],
  signInBody: [
    'We text you a six-digit code. There is no password.',
    'हामी तपाईंलाई छ अङ्कको कोड एसएमएस गर्छौं। पासवर्ड चाहिँदैन।',
  ],
  phoneLabel: ['Mobile number', 'मोबाइल नम्बर'],
  phoneHint: ['Ten digits, starting 98 or 97.', 'दस अङ्क, ९८ वा ९७ बाट सुरु हुने।'],
  sendCode: ['Send me a code', 'कोड पठाउनुहोस्'],
  sending: ['Sending…', 'पठाउँदै…'],
  codeLabel: ['The six-digit code', 'छ अङ्कको कोड'],
  codeSentTo: ['Sent to {phone}.', '{phone} मा पठाइयो।'],
  changeNumber: ['Use a different number', 'अर्को नम्बर प्रयोग गर्नुहोस्'],
  verify: ['Sign in', 'साइन इन'],
  verifying: ['Checking…', 'जाँच्दै…'],
  resend: ['Send it again', 'फेरि पठाउनुहोस्'],
  neverShare: [
    'The clinic will never ask you for this code.',
    'क्लिनिकले तपाईंसँग यो कोड कहिल्यै माग्दैन।',
  ],

  // --- bill / slip ----------------------------------------------------------
  billTitle: ['Appointment slip', 'अपोइन्टमेन्ट पर्ची'],
  billBooked: ['Booked', 'बुक भयो'],
  billPending: ['Waiting for the doctor to confirm', 'डाक्टरको पुष्टि पर्खँदै'],
  billPendingBody: [
    'You will get an SMS the moment she confirms it. The time is held for you until then.',
    'उहाँले पुष्टि गर्ने बित्तिकै तपाईंलाई एसएमएस आउनेछ। तबसम्म यो समय तपाईंकै लागि रोकिएको छ।',
  ],
  billConfirmedBody: [
    'Show this slip — printed or on your phone — at the clinic desk.',
    'यो पर्ची — प्रिन्ट गरेको वा फोनमै — क्लिनिकको काउन्टरमा देखाउनुहोस्।',
  ],
  billRef: ['Reference', 'सन्दर्भ नम्बर'],
  billPatient: ['Patient', 'बिरामी'],
  billIssued: ['Issued', 'जारी मिति'],
  billAmount: ['Amount due', 'तिर्नुपर्ने रकम'],
  billPayAtDesk: ['Payable at the clinic desk', 'क्लिनिकको काउन्टरमा तिर्नुपर्ने'],
  billPaid: ['Paid', 'भुक्तानी भयो'],
  billScan: ['Scan at the desk', 'काउन्टरमा स्क्यान गर्नुहोस्'],
  print: ['Print / Save as PDF', 'प्रिन्ट / PDF सुरक्षित'],
  copyLink: ['Copy link', 'लिङ्क कपी गर्नुहोस्'],
  linkCopied: ['Link copied', 'लिङ्क कपी भयो'],
  goToAccount: ['Go to my account', 'मेरो खातामा जानुहोस्'],
  arriveEarly: [
    'Please arrive ten minutes early. Bring any recent lab reports.',
    'कृपया दस मिनेट अगावै आउनुहोस्। हालैका ल्याब रिपोर्टहरू लिएर आउनुहोस्।',
  ],

  // --- patient account ------------------------------------------------------
  accountTitle: ['My account', 'मेरो खाता'],
  tabAppointments: ['Appointments', 'अपोइन्टमेन्ट'],
  tabHistory: ['Visit history', 'भेटको इतिहास'],
  tabPrescriptions: ['Prescriptions', 'औषधि'],
  tabReports: ['Reports', 'रिपोर्ट'],
  tabAdvice: ['Doctor\'s advice', 'डाक्टरको सल्लाह'],
  yourName: ['Your name', 'तपाईंको नाम'],
  yourNameHint: [
    'The name the clinic calls you by. Your number cannot be changed here — ring the clinic.',
    'क्लिनिकले तपाईंलाई बोलाउने नाम। नम्बर यहाँबाट बदल्न मिल्दैन — क्लिनिकमा फोन गर्नुहोस्।',
  ],
  upcoming: ['Upcoming', 'आउँदै गरेको'],
  pastVisits: ['Past visits', 'बितेका भेटहरू'],
  noUpcoming: ['No appointment booked.', 'कुनै अपोइन्टमेन्ट बुक गरिएको छैन।'],
  noPast: ['No visits yet.', 'अहिलेसम्म कुनै भेट भएको छैन।'],
  bookOne: ['Book one', 'बुक गर्नुहोस्'],
  viewSlip: ['View slip', 'पर्ची हेर्नुहोस्'],
  reschedule: ['Change time', 'समय परिवर्तन'],
  cancelVisit: ['Cancel', 'रद्द गर्नुहोस्'],
  confirmCancel: [
    'Cancel this appointment? The time goes back to other patients.',
    'यो अपोइन्टमेन्ट रद्द गर्ने? यो समय अरू बिरामीलाई उपलब्ध हुनेछ।',
  ],
  rescheduleTitle: ['Move this appointment', 'यो अपोइन्टमेन्ट सार्नुहोस्'],
  rescheduleNote: [
    'A moved appointment needs the doctor\'s nod again.',
    'सारिएको अपोइन्टमेन्टलाई डाक्टरको पुनः स्वीकृति चाहिन्छ।',
  ],
  moveHere: ['Move to this time', 'यही समयमा सार्नुहोस्'],
  statusPending: ['Awaiting confirmation', 'पुष्टि पर्खँदै'],
  statusConfirmed: ['Confirmed', 'पुष्टि भयो'],
  statusDeclined: ['Not confirmed', 'पुष्टि भएन'],
  statusCancelled: ['Cancelled', 'रद्द भयो'],
  doctorNote: ['The doctor\'s note', 'डाक्टरको नोट'],
  noNoteYet: ['Nothing written for this visit.', 'यस भेटका लागि केही लेखिएको छैन।'],
  prescribedOn: ['Prescribed {date}', '{date} मा लेखिएको'],
  noPrescriptions: ['No prescriptions yet.', 'अहिलेसम्म कुनै औषधि लेखिएको छैन।'],
  medicine: ['Medicine', 'औषधि'],
  dose: ['Dose', 'मात्रा'],
  noReports: ['No reports filed.', 'कुनै रिपोर्ट राखिएको छैन।'],
  uploadReport: ['Add a lab report', 'ल्याब रिपोर्ट थप्नुहोस्'],
  chooseFile: ['Choose a file', 'फाइल छान्नुहोस्'],
  fileHint: ['PDF, JPG or PNG, up to 5 MB.', 'PDF, JPG वा PNG, ५ MB सम्म।'],
  reportNote: ['What is this report?', 'यो कस्तो रिपोर्ट हो?'],
  upload: ['Upload', 'अपलोड गर्नुहोस्'],
  uploading: ['Uploading…', 'अपलोड हुँदै…'],
  openFile: ['Open', 'खोल्नुहोस्'],
  filedByDoctor: ['Filed by the clinic', 'क्लिनिकले राखेको'],
  filedByYou: ['You uploaded this', 'तपाईंले अपलोड गर्नुभएको'],
  filedByPatient: ['Uploaded by the patient', 'बिरामीले अपलोड गरेको'],
  noAdvice: ['The doctor has not written any advice yet.', 'डाक्टरले अहिलेसम्म कुनै सल्लाह लेख्नुभएको छैन।'],
  adviceFor: ['Advice for {name}', '{name} का लागि सल्लाह'],
  updatedOn: ['Updated {date}', '{date} मा अद्यावधिक'],

  // --- doctor: dashboard ----------------------------------------------------
  dashboardTitle: ['Today at the clinic', 'आजको क्लिनिक'],
  today: ['Today', 'आज'],
  waitingOnYou: ['Waiting on you', 'तपाईंको स्वीकृति पर्खँदै'],
  noRequests: ['No requests waiting.', 'कुनै अनुरोध पर्खिरहेको छैन।'],
  waitingMinutes: ['waiting {n} min', '{n} मिनेटदेखि पर्खँदै'],
  accept: ['Accept', 'स्वीकार'],
  decline: ['Decline', 'अस्वीकार'],
  theDay: ['The day', 'दिनभरको तालिका'],
  free: ['Free', 'खाली'],
  dayBlocked: ['The clinic is closed on this day.', 'यस दिन क्लिनिक बन्द छ।'],
  noAgenda: ['Nothing booked, and no open hours.', 'केही बुक भएको छैन, खुल्ने समय पनि छैन।'],
  bookedCount: ['{n} booked', '{n} बुक भएको'],
  markPaid: ['Mark paid', 'भुक्तानी भएको जनाउनुहोस्'],
  markUnpaid: ['Mark unpaid', 'भुक्तानी नभएको जनाउनुहोस्'],
  openRecord: ['Open record', 'रेकर्ड खोल्नुहोस्'],
  calendar: ['Calendar', 'पात्रो'],
  prevMonth: ['Previous month', 'अघिल्लो महिना'],
  nextMonth: ['Next month', 'अर्को महिना'],

  // --- doctor: schedule -----------------------------------------------------
  navSchedule: ['Schedule', 'तालिका'],
  scheduleTitle: ['My schedule', 'मेरो तालिका'],
  openingHoursNote: [
    'Leave a day empty to close it. Patients can only book inside these hours.',
    'बन्द गर्न दिनको समय खाली छोड्नुहोस्। बिरामीले यही समयभित्र मात्र बुक गर्न सक्छन्।',
  ],
  opensAt: ['Opens', 'खुल्ने'],
  closesAt: ['Closes', 'बन्द हुने'],
  breakLabel: ['Break', 'विश्राम'],
  closedDay: ['Closed', 'बन्द'],
  clearDay: ['Close this day', 'यो दिन बन्द गर्नुहोस्'],
  consultingSettings: ['Consulting', 'परामर्श'],
  slotMinutes: ['Minutes per patient', 'प्रति बिरामी मिनेट'],
  slotMinutesNote: [
    'How long one appointment slot lasts, between 5 and 240 minutes.',
    'एक अपोइन्टमेन्ट कति लामो हुन्छ, ५ देखि २४० मिनेटसम्म।',
  ],
  clinicFeeLabel: ['Clinic fee', 'क्लिनिक शुल्क'],
  videoFeeLabel: ['Video fee', 'भिडियो शुल्क'],
  feeChangeNote: [
    'New bookings only — appointments already made keep the fee they were booked at.',
    'नयाँ बुकिङमा मात्र लागू — पहिले भइसकेका अपोइन्टमेन्टको शुल्क उस्तै रहन्छ।',
  ],
  videoEnabledLabel: ['Offer video consultations', 'भिडियो परामर्श उपलब्ध गराउने'],
  autoAcceptLabel: ['Accept bookings without asking me', 'मलाई नसोधी बुकिङ स्वीकार गर्ने'],
  partlyClosed: ['Partly closed', 'आंशिक बन्द'],
  timeOffTitle: ['Time off', 'बिदा'],
  crossOut: ['Cross out time', 'समय हटाउनुहोस्'],
  wholeDayOff: ['The whole day', 'पूरै दिन'],
  partOfDay: ['Part of the day', 'दिनको केही समय'],
  morningOff: ['Morning', 'बिहान'],
  afternoonOff: ['Afternoon', 'दिउँसो'],
  fromTime: ['From', 'देखि'],
  toTime: ['To', 'सम्म'],
  untilDate: ['Repeat until', 'यो मितिसम्म दोहोर्‍याउनुहोस्'],
  untilNote: [
    'Leave this on the same day for a one-off. A later date crosses out the same window every day up to it.',
    'एकपटकका लागि सोही मिति राख्नुहोस्। पछिको मिति राखे त्यहाँसम्म हरेक दिन उही समय हटाइन्छ।',
  ],
  reasonOptional: ['Reason', 'कारण'],
  addTimeOff: ['Cross it out', 'हटाउनुहोस्'],
  removeTimeOff: ['Put it back', 'फिर्ता ल्याउनुहोस्'],
  noTimeOff: ['Nothing crossed out yet.', 'अहिलेसम्म केही हटाइएको छैन।'],
  offOnThisDay: ['Crossed out on this day', 'यस दिन हटाइएको'],
  comingUp: ['Coming up', 'आउँदै'],
  openTimes: ['Open times', 'खुला समय'],
  dayIsClosed: ['Nothing open on this day.', 'यस दिन केही खुला छैन।'],
  slotsOpen: ['{n} open', '{n} खुला'],
  closingBookedDay: [
    'Someone is already booked on this day. Crossing it out will not move them.',
    'यस दिन कोही बुक भइसकेका छन्। समय हटाउँदा उहाँहरू आफैँ सर्दैनन्।',
  ],
  callPatient: ['Call', 'फोन गर्नुहोस्'],
  strandedTitle: ['Already booked outside these hours', 'यी समयबाहिर बुक भइसकेका'],
  strandedNote: [
    'Changing the hours does not move anyone already booked. Ring these patients.',
    'समय परिवर्तन गर्दा बुक भइसकेका बिरामी सर्दैनन्। यी बिरामीलाई फोन गर्नुहोस्।',
  ],
  saveSchedule: ['Save hours and fees', 'समय र शुल्क सुरक्षित गर्नुहोस्'],

  // --- doctor: patients -----------------------------------------------------
  patientsTitle: ['Patients', 'बिरामीहरू'],
  searchPlaceholder: ['Search by name or phone number', 'नाम वा फोन नम्बरबाट खोज्नुहोस्'],
  searchHint: [
    'A phone number finds everyone in the household.',
    'फोन नम्बरले सोही घरका सबै सदस्यलाई देखाउँछ।',
  ],
  noPatients: ['No one matches that.', 'कोही भेटिएन।'],
  allergies: ['Allergies', 'एलर्जी'],
  flags: ['Flags', 'चेतावनी'],
  assessmentTitle: ['Assessment', 'मूल्याङ्कन'],
  problemLabel: ['What is the problem?', 'समस्या के हो?'],
  progressLabel: ['How is it going?', 'अवस्था कस्तो छ?'],
  suggestionsLabel: ['What should they do?', 'उनले के गर्नुपर्छ?'],
  assessmentHint: [
    'One current answer to each — rewrite it, the patient sees the last one.',
    'हरेकको एउटा पछिल्लो उत्तर — पुनर्लेखन गर्नुहोस्, बिरामीले अन्तिम उत्तर देख्छन्।',
  ],
  neverAssessed: ['Never written', 'कहिल्यै लेखिएको छैन'],
  visitsTitle: ['Visits', 'भेटहरू'],
  noVisits: ['No visits on file.', 'कुनै भेट रेकर्डमा छैन।'],
  writeNote: ['Write the note', 'नोट लेख्नुहोस्'],
  editNote: ['Edit note', 'नोट सम्पादन'],
  newPrescription: ['Write a prescription', 'औषधि लेख्नुहोस्'],
  copyLast: ['Copy the last one', 'अघिल्लो सारि लिनुहोस्'],
  addMedicine: ['Add a medicine', 'औषधि थप्नुहोस्'],
  removeRow: ['Remove', 'हटाउनुहोस्'],
  prescriptionNote: ['A line for the patient', 'बिरामीका लागि एक हरफ'],
  sendPrescription: ['Save and text it', 'सुरक्षित गरी एसएमएस पठाउनुहोस्'],
  prescriptionSent: ['Sent to {phone}', '{phone} मा पठाइयो'],
  recordsTitle: ['Records', 'रेकर्डहरू'],
  addRecord: ['Add a record', 'रेकर्ड थप्नुहोस्'],
  recordDate: ['Date', 'मिति'],
  recordText: ['What happened?', 'के भयो?'],
  recordHint: [
    'A walk-in, a phone follow-up, or a report to file.',
    'बिना अपोइन्टमेन्ट आएको, फोन फलोअप, वा राख्नुपर्ने रिपोर्ट।',
  ],

  // --- doctor: analytics ----------------------------------------------------
  analyticsTitle: ['Clinic analytics', 'क्लिनिक तथ्याङ्क'],
  pickMonth: ['Month', 'महिना'],
  collected: ['Collected', 'उठेको रकम'],
  consultations: ['Consultations', 'परामर्श'],
  averageFee: ['Average per visit', 'प्रति भेट औसत'],
  unpaid: ['Still unpaid', 'बाँकी रकम'],
  atClinic: ['Cash at the clinic', 'क्लिनिकमा नगद'],
  wallets: ['Wallets', 'वालेट'],
  busiestHours: ['Busiest hours', 'सबैभन्दा व्यस्त समय'],
  whyTheyCame: ['Why they came', 'आउनुको कारण'],
  peopleTitle: ['People', 'व्यक्तिहरू'],
  newPatients: ['New patients', 'नयाँ बिरामी'],
  returningPatients: ['Returning', 'पुनः आएका'],
  keptTitle: ['Appointments kept', 'पूरा भएका अपोइन्टमेन्ट'],
  kept: ['Kept', 'पूरा भएको'],
  dropped: ['Dropped', 'छुटेको'],
  keptNote: [
    'A kept appointment is one that was not declined or cancelled.',
    'अस्वीकार वा रद्द नभएको अपोइन्टमेन्ट पूरा भएको मानिन्छ।',
  ],
  flaggedPatients: ['Flagged patients', 'चेतावनी भएका बिरामी'],
  flaggedNote: [
    'Everyone carrying a flag or a known allergy — the records to read twice.',
    'चेतावनी वा एलर्जी भएका सबै — दोहोर्‍याएर पढ्नुपर्ने रेकर्डहरू।',
  ],
  noFlagged: ['No one is flagged.', 'कसैलाई पनि चेतावनी राखिएको छैन।'],
  noData: ['Nothing to show for this month.', 'यस महिनाका लागि केही छैन।'],

  // --- errors ---------------------------------------------------------------
  errGeneric: ['Something went wrong. Try again.', 'केही गडबड भयो। फेरि प्रयास गर्नुहोस्।'],
  errSignInFirst: ['Sign in to see this.', 'यो हेर्न साइन इन गर्नुहोस्।'],
  errDoctorOnly: ['This part of the app is for the doctor.', 'यो भाग डाक्टरका लागि मात्र हो।'],
} as const

export type StringKey = keyof typeof strings
